#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         0
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#2e3440"
bspc config focused_border_color "#fff"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Matplotlib state=floating

#AutoStart
$HOME/.config/polybar/launch.sh
picom -f &
xrandr --output eDP --mode 1366x768 --scale 1x1 --output HDMI-A-0 --mode 1360x768 --scale 1x1 --right-of eDP &
feh --bg-fill ~/Pictures/Wallpaper/AnnapurnaMassif.jpg &
xset b off &

xrdb ~/.Xtheme1 &
killall safeeyes; safeeyes &
xsetroot -cursor_name left_ptr &
#$HOME/script/battery_status/battery-getter.sh &
$HOME/script/battery-status.sh & 
xset s off & xset -dpms &

syncthing &
#echo "/home/edsel/script/scheduler/Main.py" | at now + 2 minutes
redshift -P -O 4000
